export interface Database {
  public: {
    Tables: {
      empresas: {
        Row: {
          id: string;
          id_sequencial: number;
          nome: string;
          cnpj: string | null;
          email: string | null;
          telefone: string | null;
          endereco: string | null;
          cidade: string | null;
          estado: string | null;
          cep: string | null;
          plano: string;
          ativo: boolean;
          criado_em: string;
          atualizado_em: string;
          assinatura_id: string | null;
        };
        Insert: {
          id?: string;
          id_sequencial?: number;
          nome: string;
          cnpj?: string | null;
          email?: string | null;
          telefone?: string | null;
          endereco?: string | null;
          cidade?: string | null;
          estado?: string | null;
          cep?: string | null;
          plano?: string;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
          assinatura_id?: string | null;
        };
        Update: {
          id?: string;
          id_sequencial?: number;
          nome?: string;
          cnpj?: string | null;
          email?: string | null;
          telefone?: string | null;
          endereco?: string | null;
          cidade?: string | null;
          estado?: string | null;
          cep?: string | null;
          plano?: string;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
          assinatura_id?: string | null;
        };
      };
      perfis: {
        Row: {
          id: string;
          nome_completo: string;
          id_empresa: string;
          papel: string;
          telefone: string | null;
          ativo: boolean;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id: string;
          nome_completo: string;
          id_empresa: string;
          papel?: string;
          telefone?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          nome_completo?: string;
          id_empresa?: string;
          papel?: string;
          telefone?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      pessoas: {
        Row: {
          id: string;
          id_sequencial: number;
          id_empresa: string;
          nome_razao_social: string;
          tipo_cadastro: string;
          cpf_cnpj: string | null;
          email: string | null;
          telefone: string | null;
          endereco: string | null;
          observacoes: string | null;
          ativo: boolean;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          id_sequencial?: number;
          id_empresa: string;
          nome_razao_social: string;
          tipo_cadastro: string;
          cpf_cnpj?: string | null;
          email?: string | null;
          telefone?: string | null;
          endereco?: string | null;
          observacoes?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          id_sequencial?: number;
          id_empresa?: string;
          nome_razao_social?: string;
          tipo_cadastro?: string;
          cpf_cnpj?: string | null;
          email?: string | null;
          telefone?: string | null;
          endereco?: string | null;
          observacoes?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      clientes: {
        Row: {
          id: string;
          id_sequencial: number;
          id_empresa: string;
          nome: string;
          email: string | null;
          telefone: string | null;
          documento: string | null;
          endereco: string | null;
          cidade: string | null;
          estado: string | null;
          cep: string | null;
          ativo: boolean;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          id_sequencial?: number;
          id_empresa: string;
          nome: string;
          email?: string | null;
          telefone?: string | null;
          documento?: string | null;
          endereco?: string | null;
          cidade?: string | null;
          estado?: string | null;
          cep?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          id_sequencial?: number;
          id_empresa?: string;
          nome?: string;
          email?: string | null;
          telefone?: string | null;
          documento?: string | null;
          endereco?: string | null;
          cidade?: string | null;
          estado?: string | null;
          cep?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      fornecedores: {
        Row: {
          id: string;
          id_sequencial: number;
          id_empresa: string;
          nome: string;
          pessoa_contato: string | null;
          email: string | null;
          telefone: string | null;
          documento: string | null;
          endereco: string | null;
          cidade: string | null;
          estado: string | null;
          cep: string | null;
          ativo: boolean;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          id_sequencial?: number;
          id_empresa: string;
          nome: string;
          pessoa_contato?: string | null;
          email?: string | null;
          telefone?: string | null;
          documento?: string | null;
          endereco?: string | null;
          cidade?: string | null;
          estado?: string | null;
          cep?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          id_sequencial?: number;
          id_empresa?: string;
          nome?: string;
          pessoa_contato?: string | null;
          email?: string | null;
          telefone?: string | null;
          documento?: string | null;
          endereco?: string | null;
          cidade?: string | null;
          estado?: string | null;
          cep?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      produtos_servicos: {
        Row: {
          id: string;
          id_sequencial: number;
          id_empresa: string;
          nome: string;
          descricao: string | null;
          preco: number;
          sku: string | null;
          e_servico: boolean;
          estoque_atual: number;
          estoque_minimo: number;
          categoria: string | null;
          ativo: boolean;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          id_sequencial?: number;
          id_empresa: string;
          nome: string;
          descricao?: string | null;
          preco?: number;
          sku?: string | null;
          e_servico?: boolean;
          estoque_atual?: number;
          estoque_minimo?: number;
          categoria?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          id_sequencial?: number;
          id_empresa?: string;
          nome?: string;
          descricao?: string | null;
          preco?: number;
          sku?: string | null;
          e_servico?: boolean;
          estoque_atual?: number;
          estoque_minimo?: number;
          categoria?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      categorias: {
        Row: {
          id: string;
          id_sequencial: number;
          id_empresa: string;
          nome: string;
          tipo: string;
          cor: string;
          classificacao_dre: string | null;
          id_usuario: string | null;
          ativo: boolean;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          id_sequencial?: number;
          id_empresa: string;
          nome: string;
          tipo: string;
          cor?: string;
          classificacao_dre?: string | null;
          id_usuario?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          id_sequencial?: number;
          id_empresa?: string;
          nome?: string;
          tipo?: string;
          cor?: string;
          classificacao_dre?: string | null;
          id_usuario?: string | null;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      transacoes: {
        Row: {
          id: string;
          id_sequencial: number;
          id_empresa: string;
          valor: number;
          tipo: string;
          descricao: string;
          data_transacao: string;
          id_categoria: string | null;
          id_cliente: string | null;
          id_fornecedor: string | null;
          status: string;
          origem: string;
          observacoes: string | null;
          data_vencimento: string | null;
          id_pessoa: string | null;
          criado_em: string;
          atualizado_em: string;
          e_recorrente: boolean;
          tipo_recorrencia: string | null;
          numero_parcelas: number | null;
          parcela_atual: number | null;
          data_inicio_recorrencia: string | null;
          valor_parcela: number | null;
          id_transacao_pai: string | null;
          ativa_recorrencia: boolean;
        };
        Insert: {
          id?: string;
          id_sequencial?: number;
          id_empresa: string;
          valor: number;
          tipo: string;
          descricao: string;
          data_transacao: string;
          id_categoria?: string | null;
          id_cliente?: string | null;
          id_fornecedor?: string | null;
          status?: string;
          origem?: string;
          observacoes?: string | null;
          data_vencimento?: string | null;
          id_pessoa?: string | null;
          criado_em?: string;
          atualizado_em?: string;
          e_recorrente?: boolean;
          tipo_recorrencia?: string | null;
          numero_parcelas?: number | null;
          parcela_atual?: number | null;
          data_inicio_recorrencia?: string | null;
          valor_parcela?: number | null;
          id_transacao_pai?: string | null;
          ativa_recorrencia?: boolean;
        };
        Update: {
          id?: string;
          id_sequencial?: number;
          id_empresa?: string;
          valor?: number;
          tipo?: string;
          descricao?: string;
          data_transacao?: string;
          id_categoria?: string | null;
          id_cliente?: string | null;
          id_fornecedor?: string | null;
          status?: string;
          origem?: string;
          observacoes?: string | null;
          data_vencimento?: string | null;
          id_pessoa?: string | null;
          criado_em?: string;
          atualizado_em?: string;
          e_recorrente?: boolean;
          tipo_recorrencia?: string | null;
          numero_parcelas?: number | null;
          parcela_atual?: number | null;
          data_inicio_recorrencia?: string | null;
          valor_parcela?: number | null;
          id_transacao_pai?: string | null;
          ativa_recorrencia?: boolean;
        };
      };
      vendas: {
        Row: {
          id: string;
          id_sequencial: number;
          id_empresa: string;
          id_cliente: string;
          data_venda: string;
          subtotal: number;
          desconto: number;
          total: number;
          status: string;
          observacoes: string | null;
          ativo: boolean;
          id_pessoa: string | null;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          id_sequencial?: number;
          id_empresa: string;
          id_cliente: string;
          data_venda?: string;
          subtotal?: number;
          desconto?: number;
          total?: number;
          status?: string;
          observacoes?: string | null;
          ativo?: boolean;
          id_pessoa?: string | null;
          nome_razao_social?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          id_sequencial?: number;
          id_empresa?: string;
          id_cliente?: string;
          data_venda?: string;
          subtotal?: number;
          desconto?: number;
          total?: number;
          status?: string;
          observacoes?: string | null;
          ativo?: boolean;
          id_pessoa?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      vendas_itens: {
        Row: {
          id: string;
          id_venda: string;
          id_produto: string;
          quantidade: number;
          preco_unitario: number;
          preco_total: number;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          id_venda: string;
          id_produto: string;
          quantidade?: number;
          preco_unitario?: number;
          preco_total?: number;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          id_venda?: string;
          id_produto?: string;
          quantidade?: number;
          preco_unitario?: number;
          preco_total?: number;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      lembretes: {
        Row: {
          id: string;
          id_sequencial: number;
          id_empresa: string;
          titulo: string;
          descricao: string | null;
          data_lembrete: string;
          hora_lembrete: string | null;
          hora_lembrete: string | null;
          status: string;
          ativo: boolean;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          id_sequencial?: number;
          id_empresa: string;
          titulo: string;
          descricao?: string | null;
          data_lembrete: string;
          hora_lembrete?: string | null;
          hora_lembrete?: string | null;
          status?: string;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          id_sequencial?: number;
          id_empresa?: string;
          titulo?: string;
          descricao?: string | null;
          data_lembrete?: string;
          hora_lembrete?: string | null;
          hora_lembrete?: string | null;
          status?: string;
          ativo?: boolean;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      notificacoes: {
        Row: {
          id: string;
          id_sequencial: number;
          id_empresa: string;
          id_usuario: string;
          mensagem: string;
          tipo: string;
          id_lembrete: string | null;
          lida: boolean;
          data_envio: string;
          criado_em: string;
        };
        Insert: {
          id?: string;
          id_sequencial?: number;
          id_empresa: string;
          id_usuario: string;
          mensagem: string;
          tipo?: string;
          id_lembrete?: string | null;
          lida?: boolean;
          data_envio?: string;
          criado_em?: string;
        };
        Update: {
          id?: string;
          id_sequencial?: number;
          id_empresa?: string;
          id_usuario?: string;
          mensagem?: string;
          tipo?: string;
          id_lembrete?: string | null;
          lida?: boolean;
          data_envio?: string;
          criado_em?: string;
        };
      };
    };
    vendas: {
      Row: {
        id: string;
        id_sequencial: number;
        id_empresa: string;
        id_cliente: string;
        data_venda: string;
        subtotal: number;
        desconto: number;
        total: number;
        status: string;
        observacoes: string | null;
        ativo: boolean;
        criado_em: string;
        atualizado_em: string;
      };
      Insert: {
        id?: string;
        id_sequencial?: number;
        id_empresa: string;
        id_cliente: string;
        data_venda?: string;
        subtotal?: number;
        desconto?: number;
        total?: number;
        status?: string;
        observacoes?: string | null;
        ativo?: boolean;
        criado_em?: string;
        atualizado_em?: string;
      };
      Update: {
        id?: string;
        id_sequencial?: number;
        id_empresa?: string;
        id_cliente?: string;
        data_venda?: string;
        subtotal?: number;
        desconto?: number;
        total?: number;
        status?: string;
        observacoes?: string | null;
        ativo?: boolean;
        criado_em?: string;
        atualizado_em?: string;
      };
    };
    vendas_itens: {
      Row: {
        id: string;
        id_venda: string;
        id_produto: string;
        quantidade: number;
        preco_unitario: number;
        preco_total: number;
        criado_em: string;
        atualizado_em: string;
      };
      Insert: {
        id?: string;
        id_venda: string;
        id_produto: string;
        quantidade?: number;
        preco_unitario?: number;
        preco_total?: number;
        criado_em?: string;
        atualizado_em?: string;
      };
      Update: {
        id?: string;
        id_venda?: string;
        id_produto?: string;
        quantidade?: number;
        preco_unitario?: number;
        preco_total?: number;
        criado_em?: string;
        atualizado_em?: string;
      };
    };
    configuracoes_dre: {
      Row: {
        id: string;
        id_empresa: string;
        percentual_deducao_receita: number;
        percentual_imposto_lucro: number;
        percentual_custos_vendas: number;
        percentual_despesas_operacionais: number;
        percentual_resultado_financeiro: number;
        ativo: boolean;
        criado_em: string;
        atualizado_em: string;
      };
      Insert: {
        id?: string;
        id_empresa: string;
        percentual_deducao_receita?: number;
        percentual_imposto_lucro?: number;
        percentual_custos_vendas?: number;
        percentual_despesas_operacionais?: number;
        percentual_resultado_financeiro?: number;
        ativo?: boolean;
        criado_em?: string;
        atualizado_em?: string;
      };
      Update: {
        id?: string;
        id_empresa?: string;
        percentual_deducao_receita?: number;
        percentual_imposto_lucro?: number;
        percentual_custos_vendas?: number;
        percentual_despesas_operacionais?: number;
        percentual_resultado_financeiro?: number;
        ativo?: boolean;
        criado_em?: string;
        atualizado_em?: string;
      };
    };
  };
}